### ISSUE TITLE
Send a message to a specific queue

### ISSUE THREAD

**Issue by ruros** [php-enqueue/messenger-adapter#14]
Hi! I use RabbitMQ like amqp transport, my configuration:
```yaml
enqueue:
    transport:
        default: "amqp://guest:guest@rabbitmq:5672/%2f"

framework:
    messenger:
        transports:
             amqp: enqueue://default
```

I don't understand, how I can send different messages to different RabbitMQ queues through single bus? Could I use `TransportConfiguration` or it is only for topics? It is not clear in the documentation.
Thanks!
