### ISSUE TITLE
Topic and Queue names required for simple queues (like SQS)

### ISSUE THREAD

**Issue by AlexStansfield** [php-enqueue/messenger-adapter#16]
Took a while to figure out what was going on as we're trying to use Symfony Messenger with SQS.

SQS doesn't really have the need for topics as we're putting things into a specific queue and reading them back out of it.

We had setup our config like so:
```
enqueue:
    transport:
        default: 'sqs'
        sqs:
            key: "%env(SQS_KEY)%"
            secret: "%env(SQS_SECRET)%"
            token: null
            region: 'ap-southeast-1'
            version: '2012-11-05'

framework:
    messenger:
        transports:
            sqs: "enqueue://default?queue[name]=email_queue"
        routing:
            'App\Component\Mail\Message': sqs
```

But when trying to send to the queue we were getting messages from SQS that the queue didn't exist.

Some debugging later we found the queue was being set to "messages". Looking into the code we found this https://github.com/php-enqueue/messenger-adapter/blob/master/QueueInteropTransport.php#L109

In the SQS library both `createTopic` and `createQueue` do the same thing, create an SqsDestination with the given topic/queue name as the queue to use.

In order to make our code work we had to update our config to this:

```
            sqs: "enqueue://default?topic[name]=email_queue&queue[name]=email_queue"
```

Both are needed as while the `send` method uses the topic, the `receive` method uses the queue name instead.

This kind of setup makes sense from a RabbitMQ perspective, but seems a bit odd for something like SQS.

I was wondering if it would make more sense that if the topic name is not set then it uses the queue name instead? If not, could it be documented that this might be required as we couldn't find any reference to needing to do this.
