### ISSUE TITLE
Question about logging message consumption errors.

### ISSUE THREAD

**Issue by shulard** [php-enqueue/messenger-adapter#4]
Hello !

I've just discovered the new `symfony/messenger` ecosystem which seems pretty exciting. I've an issue (more a question than a problem) about the `QueueInteropTransport` implementation.

I'm trying to log message decoding error during the development phase but I can't find a clean way to do this. It seems related to the `try {} catch {}` used inside the `QueueInteropTransport` object.

```php
try {
    $handler($this->decoder->decode(array(
        'body' => $message->getBody(),
        'headers' => $message->getHeaders(),
        'properties' => $message->getProperties(),
    )));

    $consumer->acknowledge($message);
} catch (RejectMessageException $e) {
    $consumer->reject($message);
} catch (RequeueMessageException $e) {
    $consumer->reject($message, true);
} catch (\Throwable $e) {
    $consumer->reject($message);
}
```

Is there a way to log exception messages somewhere using configuration or by extending / decorating an object ? It seems that `Exception` messages are never sent outside of that bloc of code. I've tried most of the solution that I know today.

Actually, I'm using Symfony 4.1-BETA3 with the messenger-adapter, and the enqueue/redis connector.

**Comment by sroze** [comment]
The successes and/or exceptions should be logged for you by [Symfony's Logging middleware](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Messenger/Middleware/LoggingMiddleware.php). If you prefer another type of logging, you can simply [create your own middleware](https://symfony.com/doc/4.1/messenger.html#middleware). 

Is this enough for your requirements? :)

**Comment by shulard** [comment]
I though that the middleware only come to the party when the application dispatch the message (everything is logged at that time).

My problem here is that I can't receive exceptions when the message is consumed by the `messenger:consume-messages` command. Are the middlewares active here too ?

Actually most of the errors that I miss come from the decoding process. For example if the serialized version of the object can't be decoded, the message is dropped without any notice.

Maybe I miss something here 😄.

**Comment by shulard** [comment]
Actually, this seems to be fixed by using the PropertyNormalizer in my Symfony services configuration.

```yaml
    # Enable PropertyNormalizer on the serializer component
    # This is used inside the message transport process to serialize messages.
    serialize.property_normalize:
        class: Symfony\Component\Serializer\Normalizer\PropertyNormalizer
        public: false
        tags: [serializer.normalizer]
```

I close the issue here, maybe I'm not too familiar with the used components here.
