### ISSUE TITLE
Add --time-limit doesn't work for enqueue sqs

### ISSUE THREAD

**Issue by Spawnrad** [php-enqueue/messenger-adapter#41]
Hi,

When i use enqueue sqs the --time-limit doesn't work but it work when i use amqp.

php bin/console messenger:consume-messages feed --time-limit=10

Here my configuration

```
        "enqueue/messenger-adapter": "^0.1.2",
        "enqueue/sqs": "^0.8.41",
```

```
framework:
    messenger:
        default_bus: app.messenger.command_bus
        transports:
            feed: "%env(ENQUEUE_DSN)%?topic[name]=feed&queue[name]=feed"

       routing:
            App\Message\FeedMessage: 'feed'
        buses:
            app.messenger.command_bus:
                middleware:
                    - messenger.middleware.validation
                    - App\Middleware\RetryQueueMiddleware
            app.messenger.retry_bus: ~


enqueue:
    client: ~
    transport:
        default: 'sqs'
        sqs:
            key: "%env(AWS_KEY)%"
            secret: "%env(AWS_SECRET)%"
            region: "%env(AWS_REGION)%"
```

```
###> enqueue/sqs ###
ENQUEUE_DSN=enqueue://default
###< enqueue/sqs ###
```

Thanks for your help.
